sonar.projectKey=desafio-tecnico
sonar.organization=laisbat
sonar.projectName=desafio-tecnico
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**


sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.token=a9334692a2d2765822dccd7298fc1dbfd184bd3c

sonar.exclusions=**/*.spec.ts,**/environment*.ts,**/*.module.ts

sonar.javascript.lcov.reportPaths=coverage/desafio-tecnico/lcov.info
sonar.typescript.lcov.reportPaths=coverage/desafio-tecnico/lcov.info
